<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Shared</AssemblyName>
  </PropertyGroup>

  <!-- 빌드 직후 dll을 해당 폴더에 복사-->
  <Target Name="DistributeShared" AfterTargets="Build">
    <Copy SourceFiles="$(TargetPath)"
          DestinationFolder="$(MSBuildThisFileDirectory)../client/Assets/Plugins/" />
  </Target>

</Project>
